from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Literal

from mycopatch.core.models import Probe, RiskFinding, Spore
from mycopatch.core.paths import get_paths


def generate_timezone_probe(
    repo_root: Path | str,
    risk: RiskFinding,
    spore: Spore,
    mode: Literal["safe", "aggressive"] = "safe",
) -> Probe:
    paths = get_paths(repo_root)
    paths.generated_tests.mkdir(parents=True, exist_ok=True)
    if risk.language == "python":
        _ensure_probe_conftest(paths.generated_tests)
    slug = _slugify(risk.file_path)
    mode_suffix = "" if mode == "safe" else "_aggressive"
    prefix = _probe_prefix(risk)
    extension = ".mjs" if risk.language in {"javascript", "typescript"} else ".py"
    probe_id = f"{prefix}_{slug}{mode_suffix}"
    probe_path = paths.generated_tests / f"test_myco_{prefix}_{slug}{mode_suffix}{extension}"
    pattern = _primary_pattern(risk)

    content = _render_probe(
        probe_id=probe_id,
        target_file=risk.file_path,
        risk=risk,
        pattern=pattern,
        spore=spore,
        mode=mode,
    )
    probe_path.write_text(content, encoding="utf-8")
    explanation_path = None
    if mode == "aggressive":
        explanation_path = _write_aggressive_report(paths.generated_tests, probe_path, risk, pattern)

    return Probe(
        id=probe_id,
        risk_type=risk.risk_type,
        target_file=risk.file_path,
        path=probe_path.relative_to(paths.repo_root).as_posix(),
        evidence=risk.evidence,
        spore_name=spore.name,
        safe_default=mode == "safe",
        mode=mode,
        test_runner="node-test" if risk.language in {"javascript", "typescript"} else "pytest",
        explanation_path=explanation_path.relative_to(paths.repo_root).as_posix()
        if explanation_path
        else None,
    )


def _render_probe(
    probe_id: str,
    target_file: str,
    risk: RiskFinding,
    pattern: str,
    spore: Spore,
    mode: Literal["safe", "aggressive"],
) -> str:
    evidence_lines = "\n".join(f"# - {line}" for line in risk.evidence[:6])
    if risk.language in {"javascript", "typescript"}:
        return _render_js_ts_probe(
            probe_id=probe_id,
            target_file=target_file,
            risk=risk,
            pattern=pattern,
            spore=spore,
            mode=mode,
        )

    if mode == "aggressive":
        return _render_aggressive_probe(
            probe_id=probe_id,
            target_file=target_file,
            risk=risk,
            pattern=pattern,
            spore=spore,
            evidence_lines=evidence_lines,
        )

    return f'''"""Generated by MycoPatch.

This safe probe is an executable risk marker. It does not import application
code or perform destructive actions.
"""

from pathlib import Path

import pytest


# mycopatch_probe_id: {probe_id}
# spore: {spore.name}@{spore.version}
# risk_type: {risk.risk_type}
# target_file: {target_file}
# mode: safe
# score: {risk.score}
# confidence: {risk.confidence}
# reason: {risk.reason}
# evidence:
{evidence_lines if evidence_lines else "# - no line-level evidence captured"}


@pytest.mark.mycopatch_probe
def test_myco_static_risk_marker():
    repo_root = Path(__file__).resolve().parents[3]
    target = repo_root / {target_file!r}
    assert target.exists(), "The risky file moved or was removed; refresh MycoPatch probes."

    source = target.read_text(encoding="utf-8")
    risky_pattern = {pattern!r}
    if risky_pattern:
        assert risky_pattern in source, (
            "The original risky pattern is no longer present; "
            "refresh or retire this MycoPatch probe."
        )

    # TODO: Convert this marker into a domain regression test once the intended
    # behavior is known.
'''


def _render_js_ts_probe(
    probe_id: str,
    target_file: str,
    risk: RiskFinding,
    pattern: str,
    spore: Spore,
    mode: Literal["safe", "aggressive"],
) -> str:
    comment = "//"
    evidence_lines = "\n".join(f"{comment} - {line}" for line in risk.evidence[:6])
    assertion = (
        "assert.ok(source.includes(riskyPattern), "
        "'The original risky pattern is no longer present; refresh or retire this MycoPatch probe.');"
        if mode == "safe"
        else "assert.ok(!source.includes(riskyPattern), "
        "'Aggressive MycoPatch probe failed because the timezone/date-boundary risk marker is still present. Review the generated markdown report before changing application code.');"
    )
    mode_note = (
        "This safe probe is an executable risk marker. It does not import application code."
        if mode == "safe"
        else "AGGRESSIVE PROBE: this test intentionally fails while the risky static pattern is still present."
    )
    marker = "\n".join(
        [
            f"{comment} mycopatch_probe_id: {probe_id}",
            f"{comment} spore: {spore.name}@{spore.version}",
            f"{comment} risk_type: {risk.risk_type}",
            f"{comment} target_file: {target_file}",
            f"{comment} language: {risk.language}",
            f"{comment} mode: {mode}",
            f"{comment} score: {risk.score}",
            f"{comment} confidence: {risk.confidence}",
            f"{comment} reason: {risk.reason}",
            f"{comment} evidence:",
            evidence_lines if evidence_lines else f"{comment} - no line-level evidence captured",
        ]
    )
    return f'''// Generated by MycoPatch.
// {mode_note}
// It reads the target JS/TS source as text and never imports application code.

import test from 'node:test';
import assert from 'node:assert/strict';
import {{ readFileSync }} from 'node:fs';
import {{ dirname, resolve }} from 'node:path';
import {{ fileURLToPath }} from 'node:url';

{marker}

test('mycopatch js/ts timezone boundary {mode} probe', () => {{
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const repoRoot = resolve(__dirname, '../../..');
  const target = resolve(repoRoot, {json.dumps(target_file)});
  const source = readFileSync(target, 'utf8');
  const riskyPattern = {json.dumps(pattern)};

  assert.ok(riskyPattern, 'MycoPatch probe did not have a clear static pattern to check.');
  {assertion}
}});
'''


def _render_aggressive_probe(
    probe_id: str,
    target_file: str,
    risk: RiskFinding,
    pattern: str,
    spore: Spore,
    evidence_lines: str,
) -> str:
    return f'''"""Generated by MycoPatch.

AGGRESSIVE PROBE: this test intentionally fails while the risky static pattern
is still present. It is intended for local investigation, not blind CI adoption.

It does not import application code, modify source files, access the network, or
write outside `.myco/probes/generated_tests/`.
"""

from pathlib import Path

import pytest


# mycopatch_probe_id: {probe_id}
# spore: {spore.name}@{spore.version}
# risk_type: {risk.risk_type}
# target_file: {target_file}
# mode: aggressive
# score: {risk.score}
# confidence: {risk.confidence}
# reason: {risk.reason}
# evidence:
{evidence_lines if evidence_lines else "# - no line-level evidence captured"}


@pytest.mark.mycopatch_probe
@pytest.mark.mycopatch_aggressive_probe
def test_myco_static_risk_aggressive_probe():
    repo_root = Path(__file__).resolve().parents[3]
    target = repo_root / {target_file!r}
    assert target.exists(), "The risky file moved or was removed; refresh MycoPatch probes."

    source = target.read_text(encoding="utf-8")
    risky_pattern = {pattern!r}
    assert risky_pattern, "Aggressive probe did not have a clear static pattern to check."
    assert risky_pattern not in source, (
        "Aggressive MycoPatch probe failed because a "
        + {risk.risk_type!r}
        + " risk marker is still present in "
        + target.name
        + ": "
        + risky_pattern
        + ". "
        "Review the generated markdown report before changing application code."
    )
'''


def _slugify(path: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", path).strip("_").lower()
    return slug[:80] or "repo"


def _probe_prefix(risk: RiskFinding) -> str:
    if risk.language in {"javascript", "typescript"}:
        return "js_timezone_boundary"
    if risk.risk_type == "timezone_boundary":
        return "timezone_boundary"
    return f"python_{risk.risk_type}"


def _ensure_probe_conftest(generated_tests: Path) -> None:
    conftest = generated_tests / "conftest.py"
    if conftest.exists():
        content = conftest.read_text(encoding="utf-8")
        if "mycopatch_aggressive_probe" not in content:
            conftest.write_text(_probe_conftest_content(), encoding="utf-8")
        return
    conftest.write_text(_probe_conftest_content(), encoding="utf-8")


def _probe_conftest_content() -> str:
    return '''"""Pytest configuration for generated MycoPatch probes."""


def pytest_configure(config):
    config.addinivalue_line(
        "markers",
        "mycopatch_probe: generated MycoPatch probe tests",
    )
    config.addinivalue_line(
        "markers",
        "mycopatch_aggressive_probe: generated probes that may intentionally fail",
    )
'''


def _primary_pattern(risk: RiskFinding) -> str:
    for item in risk.evidence_items:
        source_pattern = _source_pattern(item.pattern)
        if source_pattern:
            return source_pattern
    if risk.risk_type in {"mutable_default_argument", "broad_exception_swallow"} and risk.evidence_items:
        return risk.evidence_items[0].snippet
    text = "\n".join(risk.evidence)
    for pattern in ["datetime.utcnow", "date.today", "datetime.now", "datetime(", "replace(tzinfo"]:
        if pattern in text:
            return pattern
    return ""


def _source_pattern(pattern: str) -> str:
    return {
        "datetime.utcnow()": "datetime.utcnow",
        "date.today()": "date.today",
        "datetime.now()": "datetime.now",
        "datetime(...)": "datetime(",
        "replace(tzinfo=...)": "replace(tzinfo",
        "new Date()": "new Date(",
        'new Date("YYYY-MM-DD")': "new Date(",
        "Date.now()": "Date.now",
        "Date.parse(...)": "Date.parse",
        "getDate()": ".getDate(",
        "getMonth()": ".getMonth(",
        "getFullYear()": ".getFullYear(",
        "getHours()": ".getHours(",
        "getMinutes()": ".getMinutes(",
        "getSeconds()": ".getSeconds(",
        "setDate()": ".setDate(",
        "setMonth()": ".setMonth(",
        "setFullYear()": ".setFullYear(",
        "setHours()": ".setHours(",
        "setMinutes()": ".setMinutes(",
        "setSeconds()": ".setSeconds(",
    }.get(pattern, "")


def _write_aggressive_report(
    generated_tests: Path,
    probe_path: Path,
    risk: RiskFinding,
    pattern: str,
) -> Path:
    report_path = probe_path.with_suffix(".md")
    evidence = "\n".join(f"- `{item}`" for item in risk.evidence[:8])
    steps = "\n".join(f"- {step}" for step in risk.recommended_review_steps)
    report_path.write_text(
        f"""# MycoPatch Aggressive Probe Report

- Probe: `{probe_path.name}`
- Target file: `{risk.file_path}`
- Risk type: `{risk.risk_type}`
- Score: {risk.score}
- Confidence: {risk.confidence}
- Static pattern checked: `{pattern or 'none'}`

## Why This Probe May Fail

This aggressive probe intentionally fails while the static risk marker remains
in the target file. It is evidence for human review, not an automatic patch.

## Evidence

{evidence if evidence else "- No line-level evidence captured."}

## Recommended Human Review Steps

{steps if steps else "- Confirm intended behavior and add a regression test."}

## Safety Boundary

The generated test reads the target file only. It does not import application
code, modify source files, use the network, or write outside
`.myco/probes/generated_tests/`.
""",
        encoding="utf-8",
    )
    return report_path
