from __future__ import annotations

import re
from pathlib import Path

from mycopatch.core.models import Probe, RiskFinding, Spore
from mycopatch.core.paths import get_paths


def generate_timezone_probe(
    repo_root: Path | str,
    risk: RiskFinding,
    spore: Spore,
) -> Probe:
    paths = get_paths(repo_root)
    paths.generated_tests.mkdir(parents=True, exist_ok=True)
    _ensure_probe_conftest(paths.generated_tests)
    slug = _slugify(risk.file_path)
    probe_id = f"timezone_boundary_{slug}"
    probe_path = paths.generated_tests / f"test_myco_timezone_boundary_{slug}.py"
    pattern = _primary_pattern(risk)

    content = _render_probe(
        probe_id=probe_id,
        target_file=risk.file_path,
        risk=risk,
        pattern=pattern,
        spore=spore,
    )
    probe_path.write_text(content, encoding="utf-8")

    return Probe(
        id=probe_id,
        risk_type=risk.risk_type,
        target_file=risk.file_path,
        path=probe_path.relative_to(paths.repo_root).as_posix(),
        evidence=risk.evidence,
        spore_name=spore.name,
    )


def _render_probe(
    probe_id: str,
    target_file: str,
    risk: RiskFinding,
    pattern: str,
    spore: Spore,
) -> str:
    evidence_lines = "\n".join(f"# - {line}" for line in risk.evidence[:6])
    return f'''"""Generated by MycoPatch.

This safe probe is an executable risk marker. It does not import application
code or perform destructive actions.
"""

from pathlib import Path

import pytest


# mycopatch_probe_id: {probe_id}
# spore: {spore.name}@{spore.version}
# risk_type: {risk.risk_type}
# target_file: {target_file}
# score: {risk.score}
# reason: {risk.reason}
# evidence:
{evidence_lines if evidence_lines else "# - no line-level evidence captured"}


@pytest.mark.mycopatch_probe
def test_myco_timezone_boundary_marker():
    repo_root = Path(__file__).resolve().parents[3]
    target = repo_root / {target_file!r}
    assert target.exists(), "The risky file moved or was removed; refresh MycoPatch probes."

    source = target.read_text(encoding="utf-8")
    risky_pattern = {pattern!r}
    if risky_pattern:
        assert risky_pattern in source, (
            "The original risky pattern is no longer present; "
            "refresh or retire this MycoPatch probe."
        )

    # TODO: Convert this marker into a domain regression test around DST,
    # month-end, leap-day, or UTC/local midnight behavior once the intended
    # business rule is known.
'''


def _slugify(path: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", path).strip("_").lower()
    return slug[:80] or "repo"


def _ensure_probe_conftest(generated_tests: Path) -> None:
    conftest = generated_tests / "conftest.py"
    if conftest.exists():
        return
    conftest.write_text(
        '''"""Pytest configuration for generated MycoPatch probes."""


def pytest_configure(config):
    config.addinivalue_line(
        "markers",
        "mycopatch_probe: generated MycoPatch probe tests",
    )
''',
        encoding="utf-8",
    )


def _primary_pattern(risk: RiskFinding) -> str:
    text = "\n".join(risk.evidence)
    for pattern in ["datetime.utcnow", "date.today", "datetime.now", "datetime("]:
        if pattern in text:
            return pattern
    return ""
